name = "heptasean/decentralised-swap"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Decentralised peer to peer swaps for Cardano"

[repository]
user = "heptasean"
project = "decentralised-swap"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
